// <auto-generated />
namespace ComplexDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _22112018AmyMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_22112018AmyMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201811220202455_22-11-2018-A myMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
